Repository ZZANTech/ZZAN-back-office, pull requests merged in 2024-08, with the labels that each got.

#13 feat: 백오피스 기프티콘 신청내역 조회 및 수정
  package-lock.json
  package.json
  src/apis/claim.ts
  src/app/(main)/claim/_components/ClaimContainer.tsx
  src/app/(main)/claim/_components/ClaimItem.tsx
  src/app/(main)/claim/_components/ClaimList.tsx
  src/app/(main)/claim/_components/TableHeaderCell.tsx
  src/app/(main)/claim/_constant/index.ts
  src/app/(main)/claim/page.tsx
  src/app/(main)/gift/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/app/api/claim/route.ts
  src/components/PaginationContainer.tsx
  src/components/asd.tsx
  src/components/ui/table.tsx
  src/constants/index.ts
  src/store/queries/claim/useClaimMutation.ts
  src/store/queries/claim/useClaimsQuery.ts
  src/types/claim.ts
  src/types/index.ts
  src/utils/formatNumber.ts
  tsconfig.json
Labels: feature

#17 feat/quiz 퀴즈 목록 페이지
  src/apis/quiz.ts
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/(main)/quiz/_components/QuizItem.tsx
  src/app/(main)/quiz/_components/QuizList.tsx
  src/app/(main)/quiz/_constant/index.ts
  src/app/(main)/quiz/page.tsx
  src/app/api/quiz/route.ts
  src/store/queries/quiz/useQuizzesQuery.ts
  src/types/quiz.ts
Labels: feature

#18 feat/quiz 퀴즈 등록 페이지
  package-lock.json
  package.json
  src/apis/quiz.ts
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/(main)/quiz/_components/QuizItem.tsx
  src/app/(main)/quiz/_components/QuizWriteForm.tsx
  src/app/(main)/quiz/write/page.tsx
  src/app/api/quiz/route.ts
  src/components/ModalDialog.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/textarea.tsx
  src/store/queries/quiz/useQuizMutation.ts
Labels: feature

#19 feat: 기프티콘 상품 CRUD
  next.config.mjs
  package-lock.json
  package.json
  public/icons/kebab.svg
  src/apis/claim.ts
  src/apis/gift.ts
  src/app/(main)/claim/_components/ClaimItem.tsx
  src/app/(main)/claim/_components/ClaimList.tsx
  src/app/(main)/claim/_components/TableHeaderCell.tsx
  src/app/(main)/gift/_components/GiftContainer.tsx
  src/app/(main)/gift/_components/GiftForm.tsx
  src/app/(main)/gift/_components/GiftItem.tsx
  src/app/(main)/gift/_components/GiftList.tsx
  src/app/(main)/gift/constants/index.ts
  src/app/(main)/gift/edit/[giftId]/page.tsx
  src/app/(main)/gift/page.tsx
  src/app/(main)/gift/write/page.tsx
  src/app/(main)/layout.tsx
  src/app/api/gift/[giftId]/route.ts
  src/app/api/gift/route.ts
  src/components/Input/CustomInput.tsx
  src/components/ui/card.tsx
  src/constants/index.ts
  src/store/queries/claim/useClaimMutation.ts
  src/store/queries/claim/useClaimsQuery.ts
  src/store/queries/gift/useGiftMutation.ts
  src/store/queries/gift/useGiftQuery.ts
  src/store/queries/gift/useGiftsQuery.ts
  src/types/claim.type.ts
  src/types/gift.type.ts
  src/types/index.type.ts
  src/utils/sweetAlert.ts
  src/utils/uploadImage.ts
Labels: feature

#22 feat: 유저 관리
  .github/workflows/ci.yml
  package-lock.json
  src/apis/user.ts
  src/app/(main)/claim/_components/ClaimContainer.tsx
  src/app/(main)/gift/_components/GiftContainer.tsx
  src/app/(main)/gift/_components/GiftForm.tsx
  src/app/(main)/gift/_components/GiftItem.tsx
  src/app/(main)/user/_components/UserContainer.tsx
  src/app/(main)/user/_components/UserItem.tsx
  src/app/(main)/user/_components/UserList.tsx
  src/app/(main)/user/constant/index.ts
  src/app/(main)/user/page.tsx
  src/app/api/claim/route.ts
  src/app/api/user/block/[userId]/route.ts
  src/app/api/user/point/[userId]/route.ts
  src/app/api/user/route.ts
  src/app/api/user/unblock/[userId]/route.ts
  src/components/DropdownMenu.tsx
  src/components/TableContainer.tsx
  src/components/ui/alert-dialog.tsx
  src/store/queries/query.ts
  src/store/queries/user/useUserMutation.ts
  src/store/queries/user/useUserQuery.ts
  src/store/queries/user/useUsersQuery.ts
  src/types/user.type.ts
  src/utils/supabase/server.ts
  src/utils/sweetAlert.ts
Labels: feature

#25 feat/sidebar 사이드바
  public/logo.png
  src/app/(main)/_components/SidebarContainer.tsx
  src/app/layout.tsx
Labels: feature

#30 feat/vote 짠 소비 게시글 관리 페이지
  package-lock.json
  package.json
  src/apis/quiz.ts
  src/apis/vote.ts
  src/app/(main)/vote/_components/VoteContainer.tsx
  src/app/(main)/vote/_components/VoteItem.tsx
  src/app/(main)/vote/_components/VoteList.tsx
  src/app/(main)/vote/_constant/index.ts
  src/app/(main)/vote/page.tsx
  src/app/api/vote/route.ts
  src/components/SearchBar.tsx
  src/components/ui/select.tsx
  src/store/queries/vote/useVoteMutation.ts
  src/store/queries/vote/useVotesQuery.ts
  src/types/vote.type.ts
Labels: feature

#31 feat: 일간 회원가입, 짠 노하우 게시글, 소비평가 게시글, 댓글 수 조회, 퀴즈 결과 조회
  package-lock.json
  package.json
  public/icons/comment.svg
  public/icons/knowhow.svg
  public/icons/signUp.svg
  public/icons/vote.svg
  src/apis/dashboard.ts
  src/apis/user.ts
  src/app/(main)/_components/ChartTab.tsx
  src/app/(main)/_components/ChartTabContainer.tsx
  src/app/(main)/_components/CustomBarChart/CustomBarChart.tsx
  src/app/(main)/_components/CustomBarChart/CustomTooltip.tsx
  src/app/(main)/_components/CustomBarChart/CustomXAxis.tsx
  src/app/(main)/_components/CustomBarChart/CustomYAxis.tsx
  src/app/(main)/_components/DashboardContainer.tsx
  src/app/(main)/_components/QuizPieChart/CustomToolTip.tsx
  src/app/(main)/_components/QuizPieChart/DatePicker.tsx
  src/app/(main)/_components/QuizPieChart/QuizPieChart.tsx
  src/app/(main)/_constant/index.ts
  src/app/(main)/_utils/index.ts
  src/app/(main)/claim/page.tsx
  src/app/(main)/page.tsx
  src/app/api/dashboard/comment/route.ts
  src/app/api/dashboard/knowhow/route.ts
  src/app/api/dashboard/quiz/route.ts
  src/app/api/dashboard/signup/route.ts
  src/app/api/dashboard/today/comment/route.ts
  src/app/api/dashboard/today/knowhow/route.ts
  src/app/api/dashboard/today/signup/route.ts
  src/app/api/dashboard/today/vote/route.ts
  src/app/api/dashboard/vote/route.ts
  src/app/globals.css
  src/components/LoadingSpinner.tsx
  src/components/ui/calendar.tsx
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
  src/constants/index.ts
  src/store/queries/dashboard/today/useTodayCommentCountQuery.ts
  src/store/queries/dashboard/today/useTodayKnowhowCountQuery.ts
  src/store/queries/dashboard/today/useTodaySignUpCountQuery.ts
  src/store/queries/dashboard/today/useTodayVoteCountQuery.ts
  src/store/queries/dashboard/useCommentCountQuery.ts
  src/store/queries/dashboard/useKnowhowCountQuery.ts
  src/store/queries/dashboard/useQuizAnswersQuery.ts
  src/store/queries/dashboard/useSignUpCountQuery.ts
  src/store/queries/dashboard/useVoteCountQuery.ts
  src/types/dashboard.type.ts
  src/utils/getDate.ts
Labels: feature

#32 feat/knowhow 짠 노하우 게시글 관리 페이지
  src/apis/knowhow.ts
  src/app/(main)/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/knowhow/_components/KnowhowItem.tsx
  src/app/(main)/knowhow/_components/KnowhowList.tsx
  src/app/(main)/knowhow/_constant/index.ts
  src/app/(main)/knowhow/page.tsx
  src/app/api/knowhow/route.ts
  src/store/queries/knowhow/useKnowhowsQuery.ts
  src/types/knowhow.type.ts
Labels: feature

#35 feat/restrict-posts 게시글 규제 처리
  src/apis/knowhow.ts
  src/apis/vote.ts
  src/app/(main)/knowhow/_components/KnowhowItem.tsx
  src/app/(main)/vote/_components/VoteItem.tsx
  src/app/(main)/vote/_components/VoteList.tsx
  src/app/api/knowhow/[knowhowId]/route.ts
  src/app/api/vote/[voteId]/route.ts
  src/components/BanToggleButton.tsx
  src/store/queries/knowhow/useKnowhowMutation.ts
  src/store/queries/vote/useVoteMutation.ts
  src/types/supabase.ts
Labels: feature

#39 feat: display comments and block comment
  src/apis/comment.ts
  src/app/(main)/_components/SidebarContainer.tsx
  src/app/(main)/claim/_components/TableHeaderCell.tsx
  src/app/(main)/comment/_components/CommentContainer.tsx
  src/app/(main)/comment/_components/CommentItem.tsx
  src/app/(main)/comment/_components/CommentTooltip.tsx
  src/app/(main)/comment/constant/index.ts
  src/app/(main)/comment/page.tsx
  src/app/(main)/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/knowhow/_components/KnowhowItem.tsx
  src/app/(main)/knowhow/_constant/index.ts
  src/app/(main)/layout.tsx
  src/app/(main)/vote/_components/VoteContainer.tsx
  src/app/api/comment/[commentId]/route.ts
  src/app/api/comment/route.ts
  src/app/loading.tsx
  src/components/SearchBar.tsx
  src/components/TableContainer.tsx
  src/constants/index.ts
  src/store/queries/comment/useCommentMutation.ts
  src/store/queries/comment/useCommentsQuery.ts
  src/types/comment.ts
  src/types/supabase.ts
Labels: feature

#42 feat: 유저, 기프티콘 신청내역 검색기능 / refactor: 라우트핸들러 리팩토링
  src/apis/claim.ts
  src/apis/comment.ts
  src/apis/dashboard.ts
  src/apis/gift.ts
  src/apis/user.ts
  src/apis/vote.ts
  src/app/(main)/claim/_components/ClaimContainer.tsx
  src/app/(main)/claim/_components/ClaimItem.tsx
  src/app/(main)/claim/_constant/index.ts
  src/app/(main)/claim/page.tsx
  src/app/(main)/comment/_components/CommentContainer.tsx
  src/app/(main)/comment/_components/CommentItem.tsx
  src/app/(main)/gift/_components/GiftContainer.tsx
  src/app/(main)/gift/edit/[giftId]/page.tsx
  src/app/(main)/user/_components/UserContainer.tsx
  src/app/(main)/user/constant/index.ts
  src/app/api/claim/route.ts
  src/app/api/comment/[commentId]/route.ts
  src/app/api/comment/route.ts
  src/app/api/dashboard/comment/route.ts
  src/app/api/dashboard/cumulative/signup/route.ts
  src/app/api/dashboard/knowhow/route.ts
  src/app/api/dashboard/signup/route.ts
  src/app/api/dashboard/today/comment/route.ts
  src/app/api/dashboard/today/knowhow/route.ts
  src/app/api/dashboard/today/signup/route.ts
  src/app/api/dashboard/today/vote/route.ts
  src/app/api/dashboard/vote/route.ts
  src/app/api/gift/[giftId]/route.ts
  src/app/api/gift/route.ts
  src/app/api/knowhow/route.ts
  src/app/api/quiz/route.ts
  src/app/api/route.ts
  src/app/api/user/block/[userId]/route.ts
  src/app/api/user/point/[userId]/route.ts
  src/app/api/user/route.ts
  src/app/api/user/unblock/[userId]/route.ts
  src/app/api/vote/route.ts
  src/components/SearchBar.tsx
  src/components/TableContainer.tsx
  src/store/queries/claim/useClaimsQuery.ts
  src/store/queries/user/useUserMutation.ts
  src/store/queries/user/useUsersQuery.ts
  src/types/supabase.ts
  src/utils/asd.ts
Labels: feature

#43 feat/login 로그인/로그아웃
  src/apis/auth.ts
  src/apis/quiz.ts
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/login/page.tsx
  src/app/(main)/_components/SidebarContainer.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/quiz/_components/QuizItem.tsx
  src/app/(main)/quiz/_components/QuizList.tsx
  src/app/(main)/quiz/_components/QuizWriteForm.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/layout.tsx
  src/store/queries/auth/useLoginMutation.ts
  src/store/queries/auth/useLogoutMutation.ts
  src/store/queries/quiz/useQuizMutation.ts
  src/types/quiz.type.ts
  src/utils/supabase/middleware.ts
Labels: feature

#46 fix: 배포된 사이트에서 대시보드 데이터가 정상적으로 반영되지 않는 문제 해결 #45
  src/apis/dashboard.ts
  src/app/(main)/_components/DashboardContainer.tsx
  src/utils/revalidation.ts
Labels: bug

#47 dev -> main 재배포
  src/apis/dashboard.ts
  src/app/(main)/_components/DashboardContainer.tsx
  src/utils/revalidation.ts
Labels: feature

#54 fix: 배포환경 대시보드 디버깅을위한 코드변경
  src/app/api/claim/route.ts
  src/app/api/dashboard/knowhow/route.ts
  src/components/TableContainer.tsx
  src/utils/getDate.ts
Labels: bug

#56 fix: 배포환경 대시보드 디버깅을위한 코드변경
  src/utils/getDate.ts
Labels: bug

#58 fix: 배포환경 대시보드 디버깅을위한 코드변경 (startDate timezone 변경 확인 후 기존 api 적용 시도)
  src/app/api/dashboard/knowhow/route.ts
Labels: bug

#59 배포환경 대시보드 디버깅을 위한 재배포
  src/app/api/dashboard/knowhow/route.ts
  src/utils/getDate.ts
Labels: bug

#60 fix: 배포환경 대시보드 디버깅을위한 코드변경 (startDate timezone 변경 확인 후 기존 api 적용 시도)
  src/app/api/dashboard/knowhow/route.ts
Labels: bug

#61 배포환경 대시보드 디버깅을 위한 재배포 (#59)
  src/app/api/dashboard/knowhow/route.ts
Labels: bug

#62 fix: 디버깅용 콘솔 추가
  src/app/api/dashboard/knowhow/route.ts
  src/utils/getDate.ts
Labels: bug

#63 디버깅을 위한 재배포
  src/app/api/dashboard/knowhow/route.ts
  src/utils/getDate.ts
Labels: bug

#66 fix: 대시보드 timezone 문제 수정
  src/app/api/dashboard/comment/route.ts
  src/app/api/dashboard/knowhow/route.ts
  src/app/api/dashboard/signup/route.ts
  src/app/api/dashboard/today/comment/route.ts
  src/app/api/dashboard/today/knowhow/route.ts
  src/app/api/dashboard/today/signup/route.ts
  src/app/api/dashboard/today/vote/route.ts
  src/app/api/dashboard/vote/route.ts
  src/utils/getDate.ts
Labels: bug

#68 fix: 대시보드 퀴즈항목 타임존 재설정
  src/app/api/dashboard/knowhow/route.ts
  src/app/api/dashboard/quiz/route.ts
  src/utils/getDate.ts
Labels: bug

#76 feat: 기본 메타데이터 설정, 자잘한 UI 수정 등
  src/apis/comment.ts
  src/app/(main)/_components/LineChartContainer.tsx
  src/app/(main)/_components/SidebarContainer.tsx
  src/app/(main)/claim/_components/ClaimContainer.tsx
  src/app/(main)/claim/_components/ClaimItem.tsx
  src/app/(main)/claim/_constant/index.ts
  src/app/(main)/claim/page.tsx
  src/app/(main)/comment/_components/CommentContainer.tsx
  src/app/(main)/comment/_components/CommentItem.tsx
  src/app/(main)/comment/_components/CommentTooltip.tsx
  src/app/(main)/comment/constant/index.ts
  src/app/(main)/gift/_components/GiftContainer.tsx
  src/app/(main)/gift/_components/GiftForm.tsx
  src/app/(main)/gift/_components/GiftItem.tsx
  src/app/(main)/gift/page.tsx
  src/app/(main)/gift/write/page.tsx
  src/app/(main)/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/knowhow/_components/KnowhowItem.tsx
  src/app/(main)/knowhow/_constant/index.ts
  src/app/(main)/knowhow/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/(main)/quiz/_constant/index.ts
  src/app/(main)/quiz/page.tsx
  src/app/(main)/user/_components/UserContainer.tsx
  src/app/(main)/user/constant/index.ts
  src/app/(main)/user/page.tsx
  src/app/(main)/vote/_components/VoteContainer.tsx
  src/app/(main)/vote/_components/VoteItem.tsx
  src/app/(main)/vote/_constant/index.ts
  src/app/(main)/vote/page.tsx
  src/app/api/claim/route.ts
  src/app/api/comment/route.ts
  src/app/api/dashboard/knowhow/route.ts
  src/app/api/dashboard/vote/route.ts
  src/app/api/gift/[giftId]/route.ts
  src/app/layout.tsx
  src/components/BanToggleButton.tsx
  src/components/DropdownMenu.tsx
  src/components/ToggleButton.tsx
  src/store/queries/comment/useCommentMutation.ts
  src/store/queries/comment/useCommentsQuery.ts
  src/store/queries/knowhow/useKnowhowsQuery.ts
  src/store/queries/vote/useVotesQuery.ts
  src/store/zustand/store.ts
  src/types/comment.type.ts
  src/types/dayjs-plugins.d.ts
  src/types/knowhow.type.ts
  src/types/vote.type.ts
  src/utils/getDate.ts
Labels: bug, feature

#80 fix: update claim
  src/app/(main)/claim/_components/ClaimItem.tsx
  src/app/api/claim/route.ts
  src/app/api/dashboard/knowhow/route.ts
  src/app/api/user/route.ts
Labels: bug

#82 design: Update DropdownMenu.tsx
  src/components/DropdownMenu.tsx
Labels: feature
